### ISSUE TITLE
iOS and Winphone will build faliure

### ISSUE THREAD

**Issue by bau720123** [mWater/cordova-plugin-camera-foreground#10]
hi @grassick 
I am using PGB 3.4
when I build，the ios and winphone will fail，but Android is fine

I know this plugin want to solve some problem in Android
but the plugin page that said support by android and winphone Also
https://build.phonegap.com/plugins/816

so...
is the problem cause for this ?

**Comment by grassick** [comment]
Unfortunately, I'm out of time to contribute further to this without a more clear problem report. If you have a pull request, I'm happy to have a look at it, but otherwise, I'm afraid you're on your own. 

Best wishes, Clayton

**Comment by bau720123** [comment]
hi @grassick 
sorry for let you misunderstood
I mean is...
I use PGB to build my app (build.phonegap.com)
before use your plugin，android and ios and winphone build success
after use your plugin，only ios and winphone build fail
tried many times，trust me

well..
because of you said that this plugin solve "Android" some "Capture" problem (it mean ios and winphone have no this problem right ?)
so...I just wonder
look at this
https://build.phonegap.com/plugins/816
the "Platform(s)" wrote Android, [iOS, Windows Phone 8] 
don't you think this is very strange ?

**Comment by grassick** [comment]
I copied the code from the original for iOS and Windows Phone, but I don't have the time or resources to debug it, I'm afraid. If you have a code contribution, I'll have a look!

**Comment by dgutie02** [comment]
Just as an aside, the build will fail on phonegap build if the original camera plugin is not removed. The current version, 0.1.0 as of this writing, is successfully building on my projects for all platforms.

**Comment by bau720123** [comment]
hi @dgutie02 
thanks for your solved way
by the way，I just want ask another question..
the "Camera" plugin is 0.2.9 version for now
if one day have a upgrade version，maybe 0.3.0
is the "camera-foreground" plugin still can work ?

**Comment by dgutie02** [comment]
Sorry, I'm not entirely sure what you mean -- but the cordova camera plugin is independent of this plugin. Updates to the stock plugin won't be reflected here unless someone merges those changes in.

**Comment by bau720123** [comment]
hi @dgutie02 
let me explain once again
if one day "Camera" plugin have a upgrade (for now is 0.2.9 )
https://build.phonegap.com/plugins/768
well..
is the "Foreground Camera" 3rd plugin still suitable by using PGB (build.phonegap.com)

because of you said that "the build will fail on phonegap build if the original camera plugin is not removed"

**Comment by bau720123** [comment]
hi @dgutie02 
anything update about this ?

**Comment by bau720123** [comment]
hi @dgutie02 
well...
anything update or ?

**Comment by dgutie02** [comment]
If the camera plugin updates, it does not affect this 3rd party plugin.

**Comment by bau720123** [comment]
ok
thanks @dgutie02
