### ISSUE TITLE
Can't capture more than one image per camera session.  Does a similar project for Media Capture plugin exist?

### ISSUE THREAD

**Issue by marcsyp** [mWater/cordova-plugin-camera-foreground#11]
Great to see this is being worked on for Cordova 3.  Unfortunately, I'm using Media Capture and having similar restart problems.  I need Media Capture because it allows me to capture more than one image per session and returns an array of mediaFile objects.  Is there a "foreground" version of the Media Capture plugin out there?

**Comment by grassick** [comment]
Not that I know of, I'm afraid!
