### ISSUE TITLE
Reason for android:screenOrientation="landscape"

### ISSUE THREAD

**Issue by alexandru-calinoiu** [mWater/cordova-plugin-camera-foreground#2]
Hi,

I am using your plugin in a production android app and I am wondering if there was a reason for you to use landscape as the orientation and not use something like fullSensor?

**Comment by grassick** [comment]
In our application, we usually wanted landscape photos, so this was to get around the problem of people that have auto-rotate turned off. 

Full sensor does seem like a better approach (assuming the photo orientation still works right). I'd be happy to merge a pull request if you can make the change?

**Comment by jpalermo** [comment]
I'm working on a pull request for this.

There are a number of options in the cordova camera plugin that aren't currently brought into the foreground plugin. For example the correctOrientation option.

I could copy the code in to support these, but I'm thinking it might be cleaner if I just declare a dependency on the original plugin, and then override certain methods to render the foreground camera layout.

That way all the code in onActivityResult can stay where it is.

Thoughts on this?

**Comment by grassick** [comment]
Can you declare dependencies on a specific plugin version? If not, things
could get really messy as they change the internals of the camera plugin
over time, and in that case, it might be better to have a snapshot of the
code (but isolated for easy future upgrades).

**Comment by jpalermo** [comment]
http://cordova.apache.org/docs/en/3.4.0/plugin_ref_spec.md.html#Plugin%20Specification

The plugin spec doesn't allow you to specify a dependency from the plugin repository, but you can use a url an version. So for instance this would work for locking it down to the current 0.2.7 release:

```
<dependency 
    id="org.apache.cordova.camera" 
    url="https://github.com/apache/cordova-plugin-camera" 
    commit="r0.2.7" />
```

Which seems like it would work pretty well.

**Comment by grassick** [comment]
Ok, seems like a good idea to me. As long as you can override the needed
methods, it seems a pretty elegant way to do it. I say go for it. It will
be really nice to have an improved camera plugin!
