### ISSUE TITLE
Switch to front camera

### ISSUE THREAD

**Issue by shaithana** [mWater/cordova-plugin-camera-foreground#3]
Hi, I'm looking for a way to implement a toggle button to switch the camera back/front. It's a possible implementation?

**Comment by grassick** [comment]
Yes, you could add it CameraActivity and have it use camera 1 instead of camera 0. You'd need a button that would attempt to flip it.

**Comment by shaithana** [comment]
Thank you, I found it easier to rewrite the plugin from scratch.

**Comment by grassick** [comment]
Is your version available? I'm very aware that my version is a bit dated and would love to have a replacement.

**Comment by shaithana** [comment]
Sure, I'm working on right now (just adding extra features as flash and on-tap autofocus), soon as I finish I put it here on GitHub and I'll notice you.

**Comment by grassick** [comment]
Much appreciated!

**Comment by shaithana** [comment]
Hi grassik, this my new camera for Android/Cordova https://github.com/shaithana/cordova-plugin-wezka-nativecamera

**Comment by grassick** [comment]
Fantastic! I'll look forward to checking it out shortly. If it does what we need to, I'll be happy to dump this one. 

I've noticed that some phones do not set EXIF orientation correctly (either a zero or always 1). Do you do any special checking on yours? We have a lot of mis-oriented photos because of this bug.

**Comment by shaithana** [comment]
Yes, I hope I have corrected this behavior. I have also introduced additional features such as support to the tap-focus and flash, but I have not been able to test on many devices.
I hope that you will help me!

**Comment by grassick** [comment]
Thank you, thank you for this new plugin. I'll make a note that I strongly suggest using it instead from now on. It doesn't support iOS, which I'll have to add at some point.

**Comment by shaithana** [comment]
Happy U like, thanks for contribution!
