### ISSUE TITLE
Phone Gap Build

### ISSUE THREAD

**Issue by dgutie02** [mWater/cordova-plugin-camera-foreground#4]
Hello,

 Would it be possible for you to make this plugin available on Phonegap Build as a plugin? I would like to take advantage of this plugin in order to work around the Android Camera issues of my application restarting when returning from the camera.

Thanks,

**Comment by grassick** [comment]
I tried to submit it just now and got:

"Malformed xml in plugin.xml file"

But it works fine including in my app via cordova command-line. If you have any idea what's wrong, I'd be happy to resubmit.

**Comment by dgutie02** [comment]
Thanks for looking into this, I really appreciate it. I looked around a bit, and another plugin reported a simliar issue: https://github.com/floatinghotpot/cordova-plugin-admob/issues/13

Their solution was to include xmlns:android="http://schemas.android.com/apk/res/android" on the plugin tag. If you look at their plugin.xml (https://github.com/phonegap-build/GAPlugin/blob/c928e353feb1eb75ca3979b129b10b216a27ad59/plugin.xml) you can see they added the aforementioned snippet on line 2.

I hope this helps.

**Comment by grassick** [comment]
https://build.phonegap.com/plugins/816

It's live! Thanks for the help!

**Comment by grassick** [comment]
Actually, they say it might take up to a week to review. I'll respond when it is up at last.

**Comment by dgutie02** [comment]
Wow, awesome response time! Again, I really appreciate this had my back against a wall and I believe this plugin will provide a viable solution for the camera issues our app is experiencing.

One more thing, and I can create a new issue if you prefer, do you have any plans on upgrading the plugin to be compatible with PhoneGap 3.3? I know as of PhoneGap 3.0 the plugin in architecture is vastly different. It seems like we'll have to downgrade our application to 2.9 to use this as is.

**Comment by grassick** [comment]
I'm using Cordova 3.5.0 and have no issues with the plugin. What problem are you seeing that makes it only 2.9 compatible?

**Comment by dgutie02** [comment]
It was actually just an assumption -- a poor one at that. I saw that this plugin was based off: https://code.google.com/p/foreground-camera-plugin/ and noticed that their compatibility doesn't go beyond 2.4.

**Comment by grassick** [comment]
And it's live! Hope you find it helpful!
