### ISSUE TITLE
Android app still restarts

### ISSUE THREAD

**Issue by dgutie02** [mWater/cordova-plugin-camera-foreground#5]
Hello,

 I'd like to confirm how this plugin should be used. My understanding is that if I simply include the plugin in my project (which I am doing so through phonegap build), than this plugin will solve the problem of my Application being restarted by Android when the Camera comes into the foreground.

  Is there some additional configuration or code I need to be using in order for this plugin to work?

Thanks,
David

**Comment by grassick** [comment]
Hello,

I just include the plugin in the project (and don't forget to exclude the official Phonegap plugin for the camera!) and then call it as normal. Everything should work just fine.

In my code:

```
navigator.camera.getPicture(success, error, 
   { quality: 50, destinationType: Camera.DestinationType.FILE_URI});
```

To install from the command line:

`cordova plugin add https://github.com/mWater/cordova-plugin-camera-foreground.git`
