### ISSUE TITLE
What is the real purpose of this plug-in?

### ISSUE THREAD

**Issue by bau720123** [mWater/cordova-plugin-camera-foreground#8]
hi，I am using PGB 3.4 (build.phonegap.com) and camera plugin 0.2.9
https://build.phonegap.com/plugins/768

could you be kind to tell me What is the real purpose of this plug-in ?
because of that I don't know what's the true meaning of these word
"It uses a custom activity to run in the foreground in Android to prevent Cordova from being killed"

if I use this plugin，well...
is there any teaching content about this plugin ?

**Comment by grassick** [comment]
If you use the normal plugin, your Android app might be killed when taking the picture. This is normal Android behaviour. Using this plugin avoids this.

**Comment by bau720123** [comment]
hi @grassick 
thanks for your detail Comment
well...
if the "Camera" plugin might be killed (restart again ?) when taking the picture (is there any document could prove for this ?)
whether should told to official about the issue ?

**Comment by grassick** [comment]
This should answer your questions:

http://stackoverflow.com/questions/8368091/phonegap-camera-restarts-the-application

**Comment by bau720123** [comment]
hi @grassick 
thanks for your link
according to this
https://issues.apache.org/jira/browse/CB-14

it said this issue fix by phonegap 1.6 version...
so...this issue Have not been resolved...?

another question...
if use your plugin，the original "Camera" can be abandon or Coexist ?

**Comment by grassick** [comment]
That refers to a different problem. Just use this plugin, not original.

**Comment by bau720123** [comment]
ok~
thanks @grassick
